window.CAUSAL_VIEWER_V3_DATA = {
  schema_version: "1.1",
  graph: {
    name: "Legacy Baseline Sample",
    graph_type: "MAG",
    is_time_series: false,
    description: "Sample graph for Causal Viewer v3",
    source_format: "sample",
    provenance: {
      tool: "manual"
    }
  },
  nodes: [
    { id: "Appearance", label: "Appearance", layout: { x: 0.92, y: 0.10 } },
    { id: "Content", label: "Content", layout: { x: 0.12, y: 0.48 } },
    { id: "Disruptive_Aggressive_Behavior", label: "Disruptive_Aggressive_Behavior", layout: { x: 0.28, y: 0.72 } },
    { id: "Elevated_Mood", label: "Elevated_Mood", layout: { x: 0.16, y: 0.43 } },
    { id: "Energy", label: "Energy", layout: { x: 0.25, y: 0.22 } },
    { id: "Irritability", label: "Irritability", layout: { x: 0.71, y: 0.18 } },
    { id: "Language_Thought_Disorder", label: "Language_Thought_Disorder", layout: { x: 0.08, y: 0.18 } },
    { id: "Reduced_Appetite", label: "Reduced_Appetite", layout: { x: 0.33, y: 0.78 } },
    { id: "Sadness", label: "Sadness", layout: { x: 0.21, y: 0.26 } },
    { id: "Concentration_Difficulties", label: "Concentration_Difficulties", layout: { x: 0.66, y: 0.84 } },
    { id: "Inability_to_Feel", label: "Inability_to_Feel", layout: { x: 0.14, y: 0.28 } },
    { id: "Lassitude", label: "Lassitude", layout: { x: 0.91, y: 0.86 } },
    { id: "Pessimistic_Thoughts", label: "Pessimistic_Thoughts", layout: { x: 0.10, y: 0.52 } },
    { id: "Reported_Sadness", label: "Reported_Sadness", layout: { x: 0.26, y: 0.62 } },
    { id: "Reduced_Sleep", label: "Reduced_Sleep", layout: { x: 0.72, y: 0.47 } },
    { id: "Suicidal_Thought", label: "Suicidal_Thought", layout: { x: 0.27, y: 0.31 } },
    { id: "Inner_Tension", label: "Inner_Tension", layout: { x: 0.68, y: 0.09 } },
    { id: "Sexual_Interest", label: "Sexual_Interest", layout: { x: 0.35, y: 0.56 } },
    { id: "Sleep", label: "Sleep", layout: { x: 0.30, y: 0.42 } },
    { id: "Speech", label: "Speech", layout: { x: 0.07, y: 0.23 } }
  ],
  edges: [
    { source: "Inability_to_Feel", target: "Reported_Sadness", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.66 }, weight: 0.66 },
    { source: "Irritability", target: "Disruptive_Aggressive_Behavior", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.58 }, weight: 0.58 },
    { source: "Reduced_Sleep", target: "Lassitude", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.33 }, weight: -0.33 },
    { source: "Content", target: "Language_Thought_Disorder", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.62 }, weight: 0.62 },
    { source: "Inability_to_Feel", target: "Suicidal_Thought", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.40 }, weight: 0.40 },
    { source: "Sleep", target: "Language_Thought_Disorder", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.23 }, weight: 0.23 },
    { source: "Elevated_Mood", target: "Energy", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.78 }, weight: 0.78 },
    { source: "Sadness", target: "Pessimistic_Thoughts", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.89 }, weight: 0.89 },
    { source: "Pessimistic_Thoughts", target: "Inner_Tension", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.62 }, weight: 0.62 },
    { source: "Reduced_Appetite", target: "Inner_Tension", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.45 }, weight: 0.45 },
    { source: "Elevated_Mood", target: "Content", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.37 }, weight: 0.37 },
    { source: "Reduced_Sleep", target: "Sleep", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.64 }, weight: 0.64 },
    { source: "Pessimistic_Thoughts", target: "Inability_to_Feel", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.76 }, weight: 0.76 },
    { source: "Inability_to_Feel", target: "Lassitude", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.92 }, weight: 0.92 },
    { source: "Reported_Sadness", target: "Suicidal_Thought", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.44 }, weight: 0.44 },
    { source: "Lassitude", target: "Concentration_Difficulties", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.71 }, weight: 0.71 },
    { source: "Inner_Tension", target: "Irritability", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.37 }, weight: 0.37 },
    { source: "Inner_Tension", target: "Concentration_Difficulties", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.61 }, weight: 0.61 },
    { source: "Lassitude", target: "Appearance", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.41 }, weight: 0.41 },
    { source: "Inability_to_Feel", target: "Concentration_Difficulties", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.49 }, weight: 0.49 },
    { source: "Energy", target: "Language_Thought_Disorder", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.52 }, weight: 0.52 },
    { source: "Sadness", target: "Reported_Sadness", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 1.00 }, weight: 1.00 },
    { source: "Elevated_Mood", target: "Irritability", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.55 }, weight: -0.55 },
    { source: "Pessimistic_Thoughts", target: "Reported_Sadness", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.72 }, weight: 0.72 },
    { source: "Lassitude", target: "Reported_Sadness", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.45 }, weight: 0.45 },
    { source: "Elevated_Mood", target: "Speech", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.52 }, weight: 0.52 },
    { source: "Concentration_Difficulties", target: "Language_Thought_Disorder", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.40 }, weight: 0.40 },
    { source: "Sadness", target: "Suicidal_Thought", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.70 }, weight: 0.70 },
    { source: "Elevated_Mood", target: "Appearance", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.44 }, weight: -0.44 },
    { source: "Pessimistic_Thoughts", target: "Suicidal_Thought", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.87 }, weight: 0.87 },
    { source: "Elevated_Mood", target: "Sexual_Interest", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.32 }, weight: 0.32 },
    { source: "Inability_to_Feel", target: "Reduced_Appetite", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.61 }, weight: 0.61 },
    { source: "Content", target: "Irritability", endpoints: { source: "tail", target: "arrow" }, attributes: { confidence: 0.68 }, weight: -0.68 },
    { source: "Reduced_Sleep", target: "Inner_Tension", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.13 }, weight: 0.13 },
    { source: "Reduced_Sleep", target: "Reduced_Appetite", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.16 }, weight: 0.16 },
    { source: "Sadness", target: "Reduced_Appetite", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.13 }, weight: 0.13 },
    { source: "Sadness", target: "Lassitude", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.16 }, weight: 0.16 },
    { source: "Sadness", target: "Inability_to_Feel", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.23 }, weight: 0.23 },
    { source: "Sadness", target: "Concentration_Difficulties", endpoints: { source: "arrow", target: "arrow" }, attributes: { confidence: 0.10 }, weight: 0.10 },
    { source: "Content", target: "Pessimistic_Thoughts", endpoints: { source: "tail", target: "tail" }, attributes: { confidence: 0.48 }, weight: 0.48 },
    { source: "Disruptive_Aggressive_Behavior", target: "Reported_Sadness", endpoints: { source: "tail", target: "tail" }, attributes: { confidence: 0.56 }, weight: 0.56 },
    { source: "Energy", target: "Sleep", endpoints: { source: "tail", target: "tail" }, attributes: { confidence: 0.44 }, weight: 0.44 }
  ],
  metadata: {}
};
